name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.5.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test

      - name: Build Firefox extension
        run: pnpm build-firefox && pnpm pack:xpi

      - name: Build Chromium extension
        run: pnpm build && pnpm pack:zip
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "extension/*"
          body: "Release ${{ env.RELEASE_VERSION}}"
          generateReleaseNotes: true
